version: '3'

services:
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver"
    container_name: myapp
    volumes:
      - .:/myapp
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: mypostgres
    environment:
      POSTGRES_DB: complaintmsdjango
      POSTGRES_USER: postsgres
      POSTGRES_PASSWORD: tally
